import initTemas from "./modules/themes.js";
import initTextoMaior from "./modules/size-text.js";
import initTabNav from "./modules/tab-nav.js";
import initAccordion from "./modules/accordion.js";
import initScroll from "./modules/anima-scroll.js";
import initModal from "./modules/modal.js";
import initObserve from "./modules/observe-body.js";
import initTooltip from "./modules/tooltip.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initOutsideClick from "./modules/outside-click.js";

initTemas();
initTextoMaior();
initTabNav();
initAccordion();
initScroll();
initModal();
initObserve();
initTooltip();
initMenuMobile();
initOutsideClick();
