import initTemas from "./modules/themes.js";
import initTextoMaior from "./modules/size-text.js";
import initTabNav from "./modules/tab-nav.js";
import initAccordion from "./modules/accordion.js";
import initScroll from "./modules/anima-scroll.js";
import initModal from "./modules/modal.js";
import observeBody from "./modules/observe-body.js";
import initTooltip from "./modules/tooltip.js";
import initMenuMobile from "./modules/menu-mobile.js";
import intitDropdownMenu from "./modules/dropdown-menu.js";
import initFuncionamento from "./modules/funcionamento.js";
import initValidationLogin from "./modules/validation-login.js";
import initFetchAnimais from "./modules/APIs/fetch-animais.js";

initTemas();
initTextoMaior();
initTabNav();
initAccordion();
initScroll();
initModal();
observeBody();
initTooltip();
initMenuMobile();
intitDropdownMenu();
initFuncionamento();
initValidationLogin();
initFetchAnimais();
