import initTemas from "./modules/themes.js";
import initTextoMaior from "./modules/size-text.js";
import initTabNav from "./modules/tab-nav.js";
import initAccordion from "./modules/accordion.js";
import initScroll from "./modules/anima-scroll.js";
import initModal from "./modules/modal.js";
import observeBody from "./modules/observe-body.js";
import initTooltip from "./modules/tooltip.js";
import initMenuMobile from "./modules/menu-mobile.js";
import intitDropdownMenu from "./modules/dropdown-menu.js";
import initAnimaNumeros from "./modules/anima-numeros.js";
import initFuncionamento from "./modules/funcionamento.js";

initTemas();
initTextoMaior();
initTabNav();
initAccordion();
initScroll();
initModal();
observeBody();
initTooltip();
initMenuMobile();
intitDropdownMenu();
initAnimaNumeros();
initFuncionamento();
